#This file was originally generated by PyScripter's unitest wizard

import unittest
from  ..fbcursor import *

class Testcursor(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testmethod1(self):
        pass

    def testmethod2(self):
        pass

    def testmethod3(self):
        pass

    def testmethod4(self):
        pass

if __name__ == '__main__':
    unittest.main()
